# Generated by Django 2.2.1 on 2019-10-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('auther_name', models.CharField(max_length=250)),
                ('Qty_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='books_issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=1000)),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=250)),
                ('time_issued', models.DateTimeField(auto_now=True)),
                ('time_due', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='currently_issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=1000)),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=250)),
                ('time_issued', models.DateTimeField(auto_now=True)),
                ('time_due', models.DateTimeField()),
                ('is_returned', models.BooleanField(default=False)),
            ],
        ),
    ]
