# Generated by Django 2.2.1 on 2019-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0002_auto_20191014_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='currently_issued',
            name='barcode',
            field=models.CharField(default=False, max_length=12),
            preserve_default=False,
        ),
    ]
