# Generated by Django 2.2.1 on 2019-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0004_books_issued_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Available', max_length=12),
            preserve_default=False,
        ),
    ]
