# Generated by Django 2.2.1 on 2019-10-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0005_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currently_issued',
            name='is_returned',
        ),
    ]
