# Generated by Django 2.2.1 on 2019-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0007_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_due',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='time_issued',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
