# Generated by Django 2.2.1 on 2019-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0008_auto_20191029_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books_issued',
            options={'verbose_name_plural': 'books_issued'},
        ),
        migrations.AlterModelOptions(
            name='currently_issued',
            options={'verbose_name_plural': 'currently_issued'},
        ),
        migrations.AddField(
            model_name='student',
            name='class_of',
            field=models.CharField(default='CS', max_length=4),
            preserve_default=False,
        ),
    ]
