# Generated by Django 2.2.1 on 2019-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issuer', '0009_auto_20191101_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_of',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('CS', 'CS'), ('SDP', 'SDP'), ('CND', 'CND'), ('EE', 'EE'), ('CLS', 'CLS')], default='CS', max_length=4),
        ),
    ]
